/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
module ultimate_tmr_neuron2(Clk, Reset, Enable, I_syn, V_out, u_out, Theta_out, Spike);
  wire [25:0] _00_;
  wire _01_;
  wire [25:0] _02_;
  wire _03_;
  wire [25:0] _04_;
  wire [25:0] _05_;
  wire [25:0] _06_;
  wire _07_;
  wire _08_;
  wire [25:0] _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [25:0] _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire [25:0] _25_;
  wire _26_;
  wire [25:0] _27_;
  wire _28_;
  wire [25:0] _29_;
  wire [25:0] _30_;
  wire [25:0] _31_;
  wire [25:0] _32_;
  wire [25:0] _33_;
  wire [25:0] _34_;
  wire _35_;
  wire _36_;
  wire [25:0] _37_;
  wire [25:0] _38_;
  wire [25:0] _39_;
  wire [25:0] _40_;
  wire [25:0] _41_;
  wire [25:0] _42_;
  wire [25:0] _43_;
  wire [25:0] _44_;
  wire [25:0] _45_;
  wire [25:0] _46_;
  wire [25:0] _47_;
  wire [25:0] _48_;
  wire _49_;
  wire [25:0] _50_;
  wire [25:0] _51_;
  wire _52_;
  wire [25:0] _53_;
  wire [25:0] _54_;
  wire [25:0] _55_;
  wire [25:0] _56_;
  wire [25:0] _57_;
  wire [25:0] _58_;
  wire [25:0] _59_;
  wire _60_;
  wire [25:0] _61_;
  wire _62_;
  wire [25:0] _63_;
  wire [25:0] _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire [25:0] _69_;
  wire _70_;
  wire _71_;
  wire _72_;
  wire _73_;
  wire _74_;
  wire [25:0] _75_;
  wire _76_;
  wire _77_;
  wire _78_;
  wire _79_;
  wire _80_;
  wire _81_;
  input Clk;
  wire Clk;
  input Enable;
  wire Enable;
  input [25:0] I_syn;
  wire [25:0] I_syn;
  input Reset;
  wire Reset;
  output Spike;
  reg Spike;
  output [25:0] Theta_out;
  wire [25:0] Theta_out;
  output [25:0] V_out;
  wire [25:0] V_out;
  wire [25:0] b_v;
  wire [25:0] beta_brake;
  wire [25:0] beta_brake_val;
  (* unused_bits = "0" *)
  wire [25:0] bleed_target;
  (* unused_bits = "0 1 2 3 4 5" *)
  wire [25:0] diff_u;
  (* unused_bits = "0 1 2 3 4 5" *)
  wire [25:0] du;
  (* unused_bits = "0 1 2 3 4 5" *)
  wire [25:0] dv;
  (* keep = "true" *)
  wire f_beta_a;
  (* keep = "true" *)
  wire f_beta_b;
  (* keep = "true" *)
  wire f_beta_c;
  (* keep = "true" *)
  wire f_fb_a;
  (* keep = "true" *)
  wire f_fb_b;
  (* keep = "true" *)
  wire f_fb_c;
  (* keep = "true" *)
  wire f_spk_a;
  (* keep = "true" *)
  wire f_spk_b;
  (* keep = "true" *)
  wire f_spk_c;
  (* keep = "true" *)
  wire f_umax_a;
  (* keep = "true" *)
  wire f_umax_b;
  (* keep = "true" *)
  wire f_umax_c;
  (* keep = "true" *)
  wire f_umin_a;
  (* keep = "true" *)
  wire f_umin_b;
  (* keep = "true" *)
  wire f_umin_c;
  (* keep = "true" *)
  wire f_vmax_a;
  (* keep = "true" *)
  wire f_vmax_b;
  (* keep = "true" *)
  wire f_vmax_c;
  (* keep = "true" *)
  wire f_vmin_a;
  (* keep = "true" *)
  wire f_vmin_b;
  (* keep = "true" *)
  wire f_vmin_c;
  wire [25:0] pwl_out;
  wire [22:0] simplex_theta_err;
  wire [25:0] sum_v1;
  wire [25:0] sum_v2;
  wire [25:0] term_1375;
  wire [25:0] theta_decay_a;
  wire [25:0] theta_decay_b;
  wire [25:0] theta_decay_c;
  wire [25:0] theta_err_a;
  wire [25:0] theta_err_b;
  wire [25:0] theta_err_c;
  wire [25:0] theta_jmp_a;
  wire [25:0] theta_jmp_b;
  wire [25:0] theta_jmp_c;
  wire [25:0] theta_raw_a;
  wire [25:0] theta_raw_b;
  wire [25:0] theta_raw_c;
  (* keep = "true" *)
  reg [25:0] theta_reg_a = 26'h008cccd;
  (* keep = "true" *)
  reg [25:0] theta_reg_b = 26'h008cccd;
  (* keep = "true" *)
  reg [25:0] theta_reg_c = 26'h008cccd;
  wire [25:0] u_clamped;
  wire [25:0] u_fast_bleed;
  wire [25:0] u_jump_clamped;
  wire [25:0] u_jump_raw;
  wire [25:0] u_next_raw;
  output [25:0] u_out;
  wire [25:0] u_out;
  wire [25:0] u_pre_clamp;
  (* keep = "true" *)
  reg [25:0] u_reg_a = 26'h3fe6000;
  (* keep = "true" *)
  reg [25:0] u_reg_b = 26'h3fe6000;
  (* keep = "true" *)
  reg [25:0] u_reg_c = 26'h3fe6000;
  wire [25:0] u_voted;
  wire [25:0] v_clamped;
  wire [25:0] v_next_raw;
  (* keep = "true" *)
  reg [25:0] v_reg_a = 26'h0000000;
  (* keep = "true" *)
  reg [25:0] v_reg_b = 26'h0000000;
  (* keep = "true" *)
  reg [25:0] v_reg_c = 26'h0000000;
  wire [25:0] v_shr_6;
  wire [25:0] v_voted;
  wire voted_beta;
  wire voted_fb;
  wire voted_spk;
  wire [25:0] voted_theta;
  wire voted_umax;
  wire voted_umin;
  wire voted_vmax;
  wire voted_vmin;
  assign _60_ = $signed(v_next_raw) > $signed(23'h200000);
  assign _62_ = $signed(v_next_raw) < $signed(19'h40000);
  assign f_vmin_a = _62_ ? 1'h1 : 1'h0;
  assign v_clamped = f_vmax_a ? 26'h0200000 : _64_;
  assign _00_ = v_reg_a & v_reg_b;
  assign _64_ = f_vmin_a ? 26'h3fc0000 : v_next_raw;
  assign _65_ = $signed(v_next_raw) < $signed(17'h13333);
  assign _66_ = $signed(theta_reg_a) > $signed(21'h08cccd);
  assign _67_ = _66_ & _65_;
  assign _68_ = $signed(u_voted) > $signed(18'h26000);
  assign _47_ = v_reg_b & v_reg_c;
  assign _70_ = _68_ & _67_;
  assign f_fb_a = _70_ ? 1'h1 : 1'h0;
  assign _71_ = $signed(theta_reg_b) > $signed(21'h08cccd);
  assign _72_ = _71_ & _65_;
  assign _55_ = _00_ | _47_;
  assign _73_ = _68_ & _72_;
  assign f_fb_b = _73_ ? 1'h1 : 1'h0;
  assign _74_ = $signed(theta_reg_c) > $signed(21'h08cccd);
  assign _76_ = _74_ & _65_;
  assign _57_ = v_reg_a & v_reg_c;
  assign _77_ = _68_ & _76_;
  assign f_fb_c = _77_ ? 1'h1 : 1'h0;
  assign _78_ = f_fb_a & f_fb_b;
  assign _79_ = f_fb_b & f_fb_c;
  assign _80_ = _78_ | _79_;
  assign _81_ = f_fb_a & f_fb_c;
  assign voted_fb = _80_ | _81_;
  assign v_voted = _55_ | _57_;
  assign u_pre_clamp = voted_fb ? { bleed_target[25], bleed_target[25:1] } : u_next_raw;
  assign _01_ = $signed(u_pre_clamp) > $signed(23'h200000);
  assign f_umax_a = _01_ ? 1'h1 : 1'h0;
  assign _61_ = u_reg_a & u_reg_b;
  assign _63_ = u_reg_b & u_reg_c;
  assign _03_ = $signed(u_pre_clamp) < $signed(22'h200000);
  assign f_umin_a = _03_ ? 1'h1 : 1'h0;
  assign _69_ = _61_ | _63_;
  assign _75_ = u_reg_a & u_reg_c;
  assign u_clamped = f_umax_a ? 26'h0200000 : _05_;
  assign _05_ = f_umin_a ? 26'h3e00000 : u_pre_clamp;
  assign theta_err_a = theta_reg_a - 20'h8cccd;
  assign theta_err_b = theta_reg_b - 20'h8cccd;
  assign u_voted = _69_ | _75_;
  assign theta_err_c = theta_reg_c - 20'h8cccd;
  assign theta_raw_a = theta_reg_a - { theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25:6] };
  assign theta_raw_b = theta_reg_b - { theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25:6] };
  assign theta_raw_c = theta_reg_c - { theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25:6] };
  assign _02_ = theta_reg_a & theta_reg_b;
  assign theta_jmp_a = theta_raw_a + 17'h10000;
  assign theta_jmp_b = theta_raw_b + 17'h10000;
  assign theta_jmp_c = theta_raw_c + 17'h10000;
  assign _07_ = $signed(theta_err_a) > $signed(1'h0);
  assign f_beta_a = _07_ ? 1'h1 : 1'h0;
  assign _04_ = theta_reg_b & theta_reg_c;
  assign _08_ = $signed(theta_err_b) > $signed(1'h0);
  assign f_beta_b = _08_ ? 1'h1 : 1'h0;
  assign _10_ = $signed(theta_err_c) > $signed(1'h0);
  assign f_beta_c = _10_ ? 1'h1 : 1'h0;
  assign _06_ = _02_ | _04_;
  assign _11_ = f_beta_a & f_beta_b;
  assign _12_ = f_beta_b & f_beta_c;
  assign _13_ = _11_ | _12_;
  assign _14_ = f_beta_a & f_beta_c;
  assign voted_beta = _13_ | _14_;
  assign simplex_theta_err = voted_theta[22:0] - 20'h8cccd;
  assign _09_ = theta_reg_a & theta_reg_c;
  assign beta_brake = voted_beta ? { simplex_theta_err, 3'h0 } : 26'h0000000;
  assign _15_ = u_clamped + 16'hc000;
  assign u_jump_raw = _15_ + beta_brake;
  assign _16_ = $signed(u_jump_raw) > $signed(23'h200000);
  assign u_jump_clamped = _16_ ? 26'h0200000 : u_jump_raw;
  assign _17_ = $signed(v_clamped) >= $signed(theta_raw_a);
  assign voted_theta = _06_ | _09_;
  assign f_spk_a = _17_ ? 1'h1 : 1'h0;
  assign _18_ = $signed(v_clamped) >= $signed(theta_raw_b);
  assign f_spk_b = _18_ ? 1'h1 : 1'h0;
  assign _19_ = $signed(v_clamped) >= $signed(theta_raw_c);
  assign f_spk_c = _19_ ? 1'h1 : 1'h0;
  assign _20_ = f_spk_a & f_spk_b;
  assign _21_ = f_spk_b & f_spk_c;
  assign _22_ = _20_ | _21_;
  assign _23_ = f_spk_a & f_spk_c;
  assign voted_spk = _22_ | _23_;
  assign _24_ = $signed(theta_jmp_a) > $signed(24'h400000);
  assign _25_ = _24_ ? 26'h0400000 : theta_jmp_a;
  assign _26_ = $signed(theta_jmp_b) > $signed(24'h400000);
  assign _27_ = _26_ ? 26'h0400000 : theta_jmp_b;
  assign _28_ = $signed(theta_jmp_c) > $signed(24'h400000);
  assign _29_ = _28_ ? 26'h0400000 : theta_jmp_c;
  assign pwl_out = v_voted[25] ? 26'h0000000 : _41_;
  assign _30_ = voted_spk ? 26'h0000000 : v_clamped;
  assign _31_ = voted_spk ? u_jump_clamped : u_clamped;
  assign _32_ = voted_spk ? _25_ : theta_raw_a;
  assign _33_ = voted_spk ? _27_ : theta_raw_b;
  assign _34_ = voted_spk ? _29_ : theta_raw_c;
  assign _36_ = Enable ? voted_spk : 1'h0;
  assign _35_ = $signed(v_voted) < $signed(19'h20000);
  assign _41_ = _35_ ? { 2'h0, v_voted[24:1] } : _50_;
  always @(posedge Clk, posedge Reset)
    if (Reset) Spike <= 1'h0;
    else Spike <= _36_;
  assign _37_ = Enable ? _30_ : v_reg_a;
  always @(posedge Clk, posedge Reset)
    if (Reset) v_reg_a <= 26'h0000000;
    else v_reg_a <= _37_;
  assign _38_ = Enable ? _30_ : v_reg_b;
  always @(posedge Clk, posedge Reset)
    if (Reset) v_reg_b <= 26'h0000000;
    else v_reg_b <= _38_;
  assign _39_ = Enable ? _30_ : v_reg_c;
  always @(posedge Clk, posedge Reset)
    if (Reset) v_reg_c <= 26'h0000000;
    else v_reg_c <= _39_;
  assign _40_ = Enable ? _31_ : u_reg_a;
  always @(posedge Clk, posedge Reset)
    if (Reset) u_reg_a <= 26'h3fe6000;
    else u_reg_a <= _40_;
  assign _42_ = Enable ? _31_ : u_reg_b;
  always @(posedge Clk, posedge Reset)
    if (Reset) u_reg_b <= 26'h3fe6000;
    else u_reg_b <= _42_;
  assign _43_ = Enable ? _31_ : u_reg_c;
  always @(posedge Clk, posedge Reset)
    if (Reset) u_reg_c <= 26'h3fe6000;
    else u_reg_c <= _43_;
  assign _44_ = Enable ? _32_ : theta_reg_a;
  always @(posedge Clk, posedge Reset)
    if (Reset) theta_reg_a <= 26'h008cccd;
    else theta_reg_a <= _44_;
  assign _45_ = Enable ? _33_ : theta_reg_b;
  always @(posedge Clk, posedge Reset)
    if (Reset) theta_reg_b <= 26'h008cccd;
    else theta_reg_b <= _45_;
  assign _46_ = Enable ? _34_ : theta_reg_c;
  always @(posedge Clk, posedge Reset)
    if (Reset) theta_reg_c <= 26'h008cccd;
    else theta_reg_c <= _46_;
  assign _48_ = { v_voted[24:0], 1'h0 } - 18'h30000;
  assign _49_ = $signed(v_voted) < $signed(20'h50000);
  assign _50_ = _49_ ? _48_ : _53_;
  assign _51_ = { v_voted[23:0], 2'h0 } - 20'hd0000;
  assign _52_ = $signed(v_voted) < $signed(21'h090000);
  assign _53_ = _52_ ? _51_ : _54_;
  assign _54_ = { v_voted[22:0], 3'h0 } - 22'h310000;
  assign term_1375 = { v_voted[25], v_voted[25], v_voted[25], v_voted[25:3] } + { v_voted[25], v_voted[25], v_voted[25], v_voted[25], v_voted[25], v_voted[25], v_voted[25:6] };
  assign sum_v1 = pwl_out + I_syn;
  assign _56_ = term_1375 + u_voted;
  assign sum_v2 = _56_ + 18'h20000;
  assign dv = sum_v1 - sum_v2;
  assign v_next_raw = v_voted + { dv[25], dv[25], dv[25], dv[25], dv[25], dv[25], dv[25:6] };
  assign _58_ = { v_voted[25], v_voted[25], v_voted[25:2] } - { v_voted[25], v_voted[25], v_voted[25], v_voted[25], v_voted[25:4] };
  assign b_v = _58_ + { v_voted[25], v_voted[25], v_voted[25], v_voted[25], v_voted[25], v_voted[25], v_voted[25:6] };
  assign _59_ = b_v - 26'h3fe6000;
  assign diff_u = _59_ - u_voted;
  assign du = { diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25:6] } + { diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25:8] };
  assign u_next_raw = u_voted + { du[25], du[25], du[25], du[25], du[25], du[25], du[25:6] };
  assign bleed_target = u_next_raw + 26'h3fe6000;
  assign f_vmax_a = _60_ ? 1'h1 : 1'h0;
  assign Theta_out = voted_theta;
  assign V_out = v_voted;
  assign beta_brake_val = { simplex_theta_err, 3'h0 };
  assign f_umax_b = f_umax_a;
  assign f_umax_c = f_umax_a;
  assign f_umin_b = f_umin_a;
  assign f_umin_c = f_umin_a;
  assign f_vmax_b = f_vmax_a;
  assign f_vmax_c = f_vmax_a;
  assign f_vmin_b = f_vmin_a;
  assign f_vmin_c = f_vmin_a;
  assign theta_decay_a = { theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25:6] };
  assign theta_decay_b = { theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25:6] };
  assign theta_decay_c = { theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25:6] };
  assign u_fast_bleed = { bleed_target[25], bleed_target[25:1] };
  assign u_out = u_voted;
  assign v_shr_6 = { v_voted[25], v_voted[25], v_voted[25], v_voted[25], v_voted[25], v_voted[25], v_voted[25:6] };
  assign voted_umax = f_umax_a;
  assign voted_umin = f_umin_a;
  assign voted_vmax = f_vmax_a;
  assign voted_vmin = f_vmin_a;
endmodule
