/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
module light_tmr_neuron2(Clk, Reset, Enable, I_syn, V_out, u_out, Theta_out, Spike);
  wire [25:0] _00_;
  wire _01_;
  wire [25:0] _02_;
  wire [25:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [25:0] _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire [25:0] _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire [25:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire [25:0] _24_;
  wire _25_;
  wire [25:0] _26_;
  wire _27_;
  wire _28_;
  wire [25:0] _29_;
  wire [25:0] _30_;
  wire [25:0] _31_;
  wire [25:0] _32_;
  wire [25:0] _33_;
  wire [25:0] _34_;
  wire _35_;
  wire [25:0] _36_;
  wire [25:0] _37_;
  wire [25:0] _38_;
  wire [25:0] _39_;
  wire [25:0] _40_;
  wire [25:0] _41_;
  wire [25:0] _42_;
  wire [25:0] _43_;
  wire [25:0] _44_;
  wire [25:0] _45_;
  wire [25:0] _46_;
  wire [25:0] _47_;
  wire [25:0] _48_;
  wire _49_;
  wire _50_;
  wire [25:0] _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire [25:0] _68_;
  wire _69_;
  input Clk;
  wire Clk;
  input Enable;
  wire Enable;
  input [25:0] I_syn;
  wire [25:0] I_syn;
  input Reset;
  wire Reset;
  output Spike;
  reg Spike;
  output [25:0] Theta_out;
  wire [25:0] Theta_out;
  output [25:0] V_out;
  wire [25:0] V_out;
  wire [25:0] b_v;
  wire [25:0] beta_brake;
  wire [25:0] beta_brake_val;
  (* unused_bits = "0" *)
  wire [25:0] bleed_target;
  (* unused_bits = "0 1 2 3 4 5" *)
  wire [25:0] diff_u;
  (* unused_bits = "0 1 2 3 4 5" *)
  wire [25:0] du;
  (* unused_bits = "0 1 2 3 4 5" *)
  wire [25:0] dv;
  (* keep = "true" *)
  wire f_beta_a;
  (* keep = "true" *)
  wire f_beta_b;
  (* keep = "true" *)
  wire f_beta_c;
  (* keep = "true" *)
  wire f_fb_a;
  (* keep = "true" *)
  wire f_fb_b;
  (* keep = "true" *)
  wire f_fb_c;
  (* keep = "true" *)
  wire f_spk_a;
  (* keep = "true" *)
  wire f_spk_b;
  (* keep = "true" *)
  wire f_spk_c;
  (* keep = "true" *)
  wire f_umax_a;
  (* keep = "true" *)
  wire f_umax_b;
  (* keep = "true" *)
  wire f_umax_c;
  (* keep = "true" *)
  wire f_umin_a;
  (* keep = "true" *)
  wire f_umin_b;
  (* keep = "true" *)
  wire f_umin_c;
  (* keep = "true" *)
  wire f_vmax_a;
  (* keep = "true" *)
  wire f_vmax_b;
  (* keep = "true" *)
  wire f_vmax_c;
  (* keep = "true" *)
  wire f_vmin_a;
  (* keep = "true" *)
  wire f_vmin_b;
  (* keep = "true" *)
  wire f_vmin_c;
  wire [25:0] pwl_out;
  wire [22:0] simplex_theta_err;
  wire [25:0] sum_v1;
  wire [25:0] sum_v2;
  wire [25:0] term_1375;
  wire [25:0] theta_decay_a;
  wire [25:0] theta_decay_b;
  wire [25:0] theta_decay_c;
  wire [25:0] theta_err_a;
  wire [25:0] theta_err_b;
  wire [25:0] theta_err_c;
  wire [25:0] theta_jmp_a;
  wire [25:0] theta_jmp_b;
  wire [25:0] theta_jmp_c;
  wire [25:0] theta_raw_a;
  wire [25:0] theta_raw_b;
  wire [25:0] theta_raw_c;
  (* keep = "true" *)
  reg [25:0] theta_reg_a = 26'h008cccd;
  (* keep = "true" *)
  reg [25:0] theta_reg_b = 26'h008cccd;
  (* keep = "true" *)
  reg [25:0] theta_reg_c = 26'h008cccd;
  wire [25:0] u_clamped;
  wire [25:0] u_fast_bleed;
  wire [25:0] u_jump_clamped;
  wire [25:0] u_jump_raw;
  wire [25:0] u_next_raw;
  output [25:0] u_out;
  wire [25:0] u_out;
  wire [25:0] u_pre_clamp;
  reg [25:0] u_reg = 26'h3fe6000;
  wire [25:0] v_clamped;
  wire [25:0] v_next_raw;
  reg [25:0] v_reg = 26'h0000000;
  wire [25:0] v_shr_6;
  wire voted_beta;
  wire voted_fb;
  wire voted_spk;
  wire [25:0] voted_theta;
  wire voted_umax;
  wire voted_umin;
  wire voted_vmax;
  wire voted_vmin;
  assign _43_ = theta_reg_b & theta_reg_c;
  assign _50_ = $signed(v_next_raw) < $signed(19'h40000);
  assign f_vmin_a = _50_ ? 1'h1 : 1'h0;
  assign _45_ = _00_ | _43_;
  assign v_clamped = f_vmax_a ? 26'h0200000 : _51_;
  assign _51_ = f_vmin_a ? 26'h3fc0000 : v_next_raw;
  assign _48_ = theta_reg_a & theta_reg_c;
  assign _52_ = $signed(v_next_raw) < $signed(17'h13333);
  assign _53_ = $signed(theta_reg_a) > $signed(21'h08cccd);
  assign _54_ = _53_ & _52_;
  assign _55_ = $signed(u_reg) > $signed(18'h26000);
  assign _56_ = _55_ & _54_;
  assign f_fb_a = _56_ ? 1'h1 : 1'h0;
  assign voted_theta = _45_ | _48_;
  assign _57_ = $signed(theta_reg_b) > $signed(21'h08cccd);
  assign _58_ = _57_ & _52_;
  assign _59_ = _55_ & _58_;
  assign f_fb_b = _59_ ? 1'h1 : 1'h0;
  assign _60_ = $signed(theta_reg_c) > $signed(21'h08cccd);
  assign _62_ = _60_ & _52_;
  assign _63_ = _55_ & _62_;
  assign f_fb_c = _63_ ? 1'h1 : 1'h0;
  assign _64_ = f_fb_a & f_fb_b;
  assign _65_ = f_fb_b & f_fb_c;
  assign _66_ = _64_ | _65_;
  assign _67_ = f_fb_a & f_fb_c;
  assign voted_fb = _66_ | _67_;
  assign u_pre_clamp = voted_fb ? { bleed_target[25], bleed_target[25:1] } : u_next_raw;
  assign _69_ = $signed(u_pre_clamp) > $signed(23'h200000);
  assign pwl_out = v_reg[25] ? 26'h0000000 : _68_;
  assign f_umax_a = _69_ ? 1'h1 : 1'h0;
  assign _01_ = $signed(u_pre_clamp) < $signed(22'h200000);
  assign f_umin_a = _01_ ? 1'h1 : 1'h0;
  assign u_clamped = f_umax_a ? 26'h0200000 : _03_;
  assign _61_ = $signed(v_reg) < $signed(19'h20000);
  assign _03_ = f_umin_a ? 26'h3e00000 : u_pre_clamp;
  assign theta_err_a = theta_reg_a - 20'h8cccd;
  assign theta_err_b = theta_reg_b - 20'h8cccd;
  assign theta_err_c = theta_reg_c - 20'h8cccd;
  assign _68_ = _61_ ? { 2'h0, v_reg[24:1] } : _07_;
  assign theta_raw_a = theta_reg_a - { theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25:6] };
  assign theta_raw_b = theta_reg_b - { theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25:6] };
  assign theta_raw_c = theta_reg_c - { theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25:6] };
  assign theta_jmp_a = theta_raw_a + 17'h10000;
  assign theta_jmp_b = theta_raw_b + 17'h10000;
  assign theta_jmp_c = theta_raw_c + 17'h10000;
  assign _05_ = $signed(theta_err_a) > $signed(1'h0);
  assign f_beta_a = _05_ ? 1'h1 : 1'h0;
  assign _06_ = $signed(theta_err_b) > $signed(1'h0);
  assign f_beta_b = _06_ ? 1'h1 : 1'h0;
  assign _08_ = $signed(theta_err_c) > $signed(1'h0);
  assign f_beta_c = _08_ ? 1'h1 : 1'h0;
  assign _09_ = f_beta_a & f_beta_b;
  assign _10_ = f_beta_b & f_beta_c;
  assign _11_ = _09_ | _10_;
  assign _12_ = f_beta_a & f_beta_c;
  assign voted_beta = _11_ | _12_;
  assign simplex_theta_err = voted_theta[22:0] - 20'h8cccd;
  assign beta_brake = voted_beta ? { simplex_theta_err, 3'h0 } : 26'h0000000;
  assign _13_ = u_clamped + 16'hc000;
  assign _02_ = { v_reg[24:0], 1'h0 } - 18'h30000;
  assign u_jump_raw = _13_ + beta_brake;
  assign _14_ = $signed(u_jump_raw) > $signed(23'h200000);
  assign u_jump_clamped = _14_ ? 26'h0200000 : u_jump_raw;
  assign _15_ = $signed(v_clamped) >= $signed(theta_raw_a);
  assign f_spk_a = _15_ ? 1'h1 : 1'h0;
  assign _16_ = $signed(v_clamped) >= $signed(theta_raw_b);
  assign f_spk_b = _16_ ? 1'h1 : 1'h0;
  assign _17_ = $signed(v_clamped) >= $signed(theta_raw_c);
  assign f_spk_c = _17_ ? 1'h1 : 1'h0;
  assign _19_ = f_spk_a & f_spk_b;
  assign _20_ = f_spk_b & f_spk_c;
  assign _21_ = _19_ | _20_;
  assign _22_ = f_spk_a & f_spk_c;
  assign _04_ = $signed(v_reg) < $signed(20'h50000);
  assign voted_spk = _21_ | _22_;
  assign _23_ = $signed(theta_jmp_a) > $signed(24'h400000);
  assign _24_ = _23_ ? 26'h0400000 : theta_jmp_a;
  assign _25_ = $signed(theta_jmp_b) > $signed(24'h400000);
  assign _07_ = _04_ ? _02_ : _37_;
  assign _26_ = _25_ ? 26'h0400000 : theta_jmp_b;
  assign _27_ = $signed(theta_jmp_c) > $signed(24'h400000);
  assign _29_ = _27_ ? 26'h0400000 : theta_jmp_c;
  assign _30_ = voted_spk ? 26'h0000000 : v_clamped;
  assign _31_ = voted_spk ? u_jump_clamped : u_clamped;
  assign _32_ = voted_spk ? _24_ : theta_raw_a;
  assign _33_ = voted_spk ? _26_ : theta_raw_b;
  assign _34_ = voted_spk ? _29_ : theta_raw_c;
  assign _35_ = Enable ? voted_spk : 1'h0;
  always @(posedge Clk, posedge Reset)
    if (Reset) Spike <= 1'h0;
    else Spike <= _35_;
  assign _36_ = Enable ? _30_ : v_reg;
  assign _18_ = { v_reg[23:0], 2'h0 } - 20'hd0000;
  always @(posedge Clk, posedge Reset)
    if (Reset) v_reg <= 26'h0000000;
    else v_reg <= _36_;
  assign _38_ = Enable ? _31_ : u_reg;
  always @(posedge Clk, posedge Reset)
    if (Reset) u_reg <= 26'h3fe6000;
    else u_reg <= _38_;
  assign _39_ = Enable ? _32_ : theta_reg_a;
  always @(posedge Clk, posedge Reset)
    if (Reset) theta_reg_a <= 26'h008cccd;
    else theta_reg_a <= _39_;
  assign _40_ = Enable ? _33_ : theta_reg_b;
  always @(posedge Clk, posedge Reset)
    if (Reset) theta_reg_b <= 26'h008cccd;
    else theta_reg_b <= _40_;
  assign _41_ = Enable ? _34_ : theta_reg_c;
  always @(posedge Clk, posedge Reset)
    if (Reset) theta_reg_c <= 26'h008cccd;
    else theta_reg_c <= _41_;
  assign _28_ = $signed(v_reg) < $signed(21'h090000);
  assign _37_ = _28_ ? _18_ : _42_;
  assign _42_ = { v_reg[22:0], 3'h0 } - 22'h310000;
  assign term_1375 = { v_reg[25], v_reg[25], v_reg[25], v_reg[25:3] } + { v_reg[25], v_reg[25], v_reg[25], v_reg[25], v_reg[25], v_reg[25], v_reg[25:6] };
  assign sum_v1 = pwl_out + I_syn;
  assign _44_ = term_1375 + u_reg;
  assign sum_v2 = _44_ + 18'h20000;
  assign dv = sum_v1 - sum_v2;
  assign v_next_raw = v_reg + { dv[25], dv[25], dv[25], dv[25], dv[25], dv[25], dv[25:6] };
  assign _46_ = { v_reg[25], v_reg[25], v_reg[25:2] } - { v_reg[25], v_reg[25], v_reg[25], v_reg[25], v_reg[25:4] };
  assign b_v = _46_ + { v_reg[25], v_reg[25], v_reg[25], v_reg[25], v_reg[25], v_reg[25], v_reg[25:6] };
  assign _47_ = b_v - 26'h3fe6000;
  assign diff_u = _47_ - u_reg;
  assign du = { diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25:6] } + { diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25], diff_u[25:8] };
  assign u_next_raw = u_reg + { du[25], du[25], du[25], du[25], du[25], du[25], du[25:6] };
  assign bleed_target = u_next_raw + 26'h3fe6000;
  assign _49_ = $signed(v_next_raw) > $signed(23'h200000);
  assign f_vmax_a = _49_ ? 1'h1 : 1'h0;
  assign _00_ = theta_reg_a & theta_reg_b;
  assign Theta_out = voted_theta;
  assign V_out = v_reg;
  assign beta_brake_val = { simplex_theta_err, 3'h0 };
  assign f_umax_b = f_umax_a;
  assign f_umax_c = f_umax_a;
  assign f_umin_b = f_umin_a;
  assign f_umin_c = f_umin_a;
  assign f_vmax_b = f_vmax_a;
  assign f_vmax_c = f_vmax_a;
  assign f_vmin_b = f_vmin_a;
  assign f_vmin_c = f_vmin_a;
  assign theta_decay_a = { theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25], theta_err_a[25:6] };
  assign theta_decay_b = { theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25], theta_err_b[25:6] };
  assign theta_decay_c = { theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25], theta_err_c[25:6] };
  assign u_fast_bleed = { bleed_target[25], bleed_target[25:1] };
  assign u_out = u_reg;
  assign v_shr_6 = { v_reg[25], v_reg[25], v_reg[25], v_reg[25], v_reg[25], v_reg[25], v_reg[25:6] };
  assign voted_umax = f_umax_a;
  assign voted_umin = f_umin_a;
  assign voted_vmax = f_vmax_a;
  assign voted_vmin = f_vmin_a;
endmodule
